/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: DatSketch (https://sketchfab.com/DatSketch)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/samsung-galaxy-s21-ultra-cd962832be7744efb6b37fe0ee2027e7
Title: Samsung Galaxy S21 Ultra
*/

import React, { useRef } from "react";
import { OrbitControls, useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export function Model(props) {
  const groupRef = useRef();
  const { nodes, materials } = useGLTF("/samsung_galaxy_s21_ultra.glb");

  useFrame(() => {
    if (groupRef.current) {
      groupRef.current.rotation.y += 0.01;
    }
  });

  return (
    <group ref={groupRef} {...props} dispose={null}>
      <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
        <group name="S21ULTRAfbx" rotation={[Math.PI / 2, 0, 0]}>
          <group name="S21ULTRA" scale={[-3.435, 3.435, 3.435]}>
            <mesh
              name="S21ULTRA_BodyFrame_0"
              castShadow
              receiveShadow
              geometry={nodes.S21ULTRA_BodyFrame_0.geometry}
              material={materials.BodyFrame}
            />
            <mesh
              name="S21ULTRA_Speaker_0"
              castShadow
              receiveShadow
              geometry={nodes.S21ULTRA_Speaker_0.geometry}
              material={materials.Speaker}
            />
            <mesh
              name="S21ULTRA_Chrome_0"
              castShadow
              receiveShadow
              geometry={nodes.S21ULTRA_Chrome_0.geometry}
              material={materials.Chrome}
            />
            <mesh
              name="S21ULTRA_Antennas_0"
              castShadow
              receiveShadow
              geometry={nodes.S21ULTRA_Antennas_0.geometry}
              material={materials.Antennas}
            />
            <group
              name="Camera1"
              position={[0.983, 2.035, 0.506]}
              scale={[-0.258, 0.258, 0.258]}
            >
              <mesh
                name="Camera1_BodyFrame_0"
                castShadow
                receiveShadow
                geometry={nodes.Camera1_BodyFrame_0.geometry}
                material={materials.BodyFrame}
              />
              <mesh
                name="Camera1_Camera2_0"
                castShadow
                receiveShadow
                geometry={nodes.Camera1_Camera2_0.geometry}
                material={materials.Camera2}
              />
              <mesh
                name="Camera1_Camera3_0"
                castShadow
                receiveShadow
                geometry={nodes.Camera1_Camera3_0.geometry}
                material={materials.Camera3}
              />
              <mesh
                name="Camera1_Glass_0"
                castShadow
                receiveShadow
                geometry={nodes.Camera1_Glass_0.geometry}
                material={materials.Glass}
              />
              <group name="Camera2" position={[0, 2.785, 0]}>
                <mesh
                  name="Camera2_BodyFrame_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Camera2_BodyFrame_0.geometry}
                  material={materials.BodyFrame}
                />
                <mesh
                  name="Camera2_Camera2_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Camera2_Camera2_0.geometry}
                  material={materials.Camera2}
                />
                <mesh
                  name="Camera2_Camera3_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Camera2_Camera3_0.geometry}
                  material={materials.Camera3}
                />
                <mesh
                  name="Camera2_Glass_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Camera2_Glass_0.geometry}
                  material={materials.Glass}
                />
                <mesh
                  name="Lens2_Lens_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Lens2_Lens_0.geometry}
                  material={materials.Lens}
                  position={[0, 0.004, -0.269]}
                  scale={[0.497, 0.497, 0.213]}
                />
              </group>
              <group name="Camera4" position={[2.608, -0.071, 0]} scale={0.678}>
                <mesh
                  name="Camera4_BodyFrame_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Camera4_BodyFrame_0.geometry}
                  material={materials.BodyFrame}
                />
                <mesh
                  name="Camera4_Camera3_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Camera4_Camera3_0.geometry}
                  material={materials.Camera3}
                />
                <mesh
                  name="Camera4_Camera2_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Camera4_Camera2_0.geometry}
                  material={materials.Camera2}
                />
                <mesh
                  name="Camera4_Glass_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Camera4_Glass_0.geometry}
                  material={materials.Glass}
                />
                <group
                  name="Lens4"
                  position={[0.004, 0.007, -0.275]}
                  scale={[0.421, 0.421, 0.228]}
                >
                  <mesh
                    name="Lens4_Lens_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Lens4_Lens_0.geometry}
                    material={materials.Lens}
                  />
                  <mesh
                    name="Lens4_Camera2_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Lens4_Camera2_0.geometry}
                    material={materials.Camera2}
                  />
                </group>
              </group>
              <group name="Sensor" position={[2.608, 2.844, 0]} scale={0.678}>
                <mesh
                  name="Sensor_BodyFrame_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Sensor_BodyFrame_0.geometry}
                  material={materials.BodyFrame}
                />
                <mesh
                  name="Sensor_Camera2_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Sensor_Camera2_0.geometry}
                  material={materials.Camera2}
                />
                <mesh
                  name="Sensor_Red_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Sensor_Red_0.geometry}
                  material={materials.material}
                />
                <mesh
                  name="Sensor_Glass_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Sensor_Glass_0.geometry}
                  material={materials.Glass}
                />
              </group>
              <group name="Flashh" position={[2.608, 1.416, 0]} scale={0.353}>
                <mesh
                  name="Flashh_BodyFrame_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Flashh_BodyFrame_0.geometry}
                  material={materials.BodyFrame}
                />
                <mesh
                  name="Flashh_Flash_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Flashh_Flash_0.geometry}
                  material={materials.Flash}
                />
                <mesh
                  name="Flashh_Glass_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Flashh_Glass_0.geometry}
                  material={materials.Glass}
                />
              </group>
              <group name="Camera3" position={[0, -2.861, 0]}>
                <mesh
                  name="Camera3_BodyFrame_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Camera3_BodyFrame_0.geometry}
                  material={materials.BodyFrame}
                />
                <mesh
                  name="Camera3_Camera2_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Camera3_Camera2_0.geometry}
                  material={materials.Camera2}
                />
                <mesh
                  name="Camera3_Camera3_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Camera3_Camera3_0.geometry}
                  material={materials.Camera3}
                />
                <mesh
                  name="Camera3_Lens001_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Camera3_Lens001_0.geometry}
                  material={materials["Lens.001"]}
                />
                <mesh
                  name="Camera3_Glass_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Camera3_Glass_0.geometry}
                  material={materials.Glass}
                />
              </group>
              <group
                name="Lens1"
                position={[0.002, 0, -0.269]}
                scale={[0.317, 0.317, 0.225]}
              >
                <mesh
                  name="Lens1_Lens_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Lens1_Lens_0.geometry}
                  material={materials.Lens}
                />
                <mesh
                  name="Lens1_Camera2_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Lens1_Camera2_0.geometry}
                  material={materials.Camera2}
                />
              </group>
              <group
                name="FrontCamera"
                position={[3.985, 4.506, -1.764]}
                rotation={[0, 0, Math.PI]}
                scale={[-0.734, 0.734, 0.734]}
              >
                <mesh
                  name="FrontCamera_BodyFrame_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.FrontCamera_BodyFrame_0.geometry}
                  material={materials.BodyFrame}
                />
                <mesh
                  name="FrontCamera_Camera3_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.FrontCamera_Camera3_0.geometry}
                  material={materials.Camera3}
                />
                <mesh
                  name="FrontCamera_Glass_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.FrontCamera_Glass_0.geometry}
                  material={materials.Glass}
                />
                <mesh
                  name="LensFC_Lens_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.LensFC_Lens_0.geometry}
                  material={materials.Lens}
                  position={[0, 0, 0.116]}
                  rotation={[-Math.PI, 0, 0]}
                  scale={[-0.165, 0.165, 0.09]}
                />
              </group>
            </group>
            <mesh
              name="CamModuleFrame_BodyFrame_0"
              castShadow
              receiveShadow
              geometry={nodes.CamModuleFrame_BodyFrame_0.geometry}
              material={materials.BodyFrame}
              position={[-1.006, -0.44, 0]}
              scale={[-1, 1, 1]}
            />
            <mesh
              name="CamModule_CameraModule_0"
              castShadow
              receiveShadow
              geometry={nodes.CamModule_CameraModule_0.geometry}
              material={materials.CameraModule}
              position={[-1.006, -0.44, 0.043]}
              scale={[-1, 1, 1]}
            />
            <mesh
              name="Back_Back_0"
              castShadow
              receiveShadow
              geometry={nodes.Back_Back_0.geometry}
              material={materials.Back}
            />
            <mesh
              name="Screen_Screen_0"
              castShadow
              receiveShadow
              geometry={nodes.Screen_Screen_0.geometry}
              material={materials.Screen}
            />
            <mesh
              name="ScreenBezel_ScreenBezel_0"
              castShadow
              receiveShadow
              geometry={nodes.ScreenBezel_ScreenBezel_0.geometry}
              material={materials.ScreenBezel}
            />
            <mesh
              name="VolumeButton__BodyFrame_0"
              castShadow
              receiveShadow
              geometry={nodes.VolumeButton__BodyFrame_0.geometry}
              material={materials.BodyFrame}
              position={[1.738, 1.325, 0.195]}
              rotation={[0, Math.PI / 2, 0]}
              scale={[-0.041, 0.032, 0.032]}
            />
            <mesh
              name="PowerButton_BodyFrame_0"
              castShadow
              receiveShadow
              geometry={nodes.PowerButton_BodyFrame_0.geometry}
              material={materials.BodyFrame}
              position={[1.738, 0.43, 0.195]}
              rotation={[0, Math.PI / 2, 0]}
              scale={[-0.041, 0.032, 0.032]}
            />
            <mesh
              name="Logo_BodyFrame_0"
              castShadow
              receiveShadow
              geometry={nodes.Logo_BodyFrame_0.geometry}
              material={materials.BodyFrame}
              position={[-0.111, -3.08, 0.442]}
              rotation={[-Math.PI / 2, 0, -Math.PI]}
              scale={[-0.489, 0.489, 0.489]}
            />
          </group>
        </group>
      </group>
      <OrbitControls />
    </group>
  );
}

useGLTF.preload("/samsung_galaxy_s21_ultra.glb");
